name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Verificar diretório de trabalho
        run: |
          echo "Diretório atual: $(pwd)"
          ls -la
          ls -la MarsRovers

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Verificar a existência do arquivo .sln
        run: |
          echo "Procurando o arquivo .sln"
          find . -name "*.sln"

      - name: Restaurar dependências
        run: dotnet restore MarsRovers/MarsRovers.sln

      - name: Compilar solução
        run: dotnet build MarsRovers/MarsRovers.sln --no-restore --configuration Release

      - name: Executar testes
        run: dotnet test MarsRovers/MarsRovers.sln --verbosity normal
