name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore MinhaSolucao.sln

      - name: Build
        run: dotnet build MinhaSolucao.sln --no-restore

      - name: Run tests
        run: dotnet test MarsRovers.sln --no-build --verbosity normal
